let products=[];
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function api(url,options={}){const r=await fetch(url,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d;}
async function load(){products=await api('/api/admin/products');$('inventory').innerHTML=products.map((p,i)=>`<tr><td><input data-k="name" data-i="${i}" value="${esc(p.name)}"></td><td><input data-k="category" data-i="${i}" value="${esc(p.category)}"></td><td><input type="number" step="0.01" data-k="price" data-i="${i}" value="${p.price}"></td><td><input type="number" min="0" data-k="stock" data-i="${i}" value="${p.stock}"></td><td><input type="checkbox" data-k="active" data-i="${i}" ${p.active!==false?'checked':''}></td><td><button class="danger" data-delete="${i}">Delete</button></td></tr>`).join('');}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginStatus').textContent='Signing in…';try{await api('/api/admin/login',{method:'POST',body:JSON.stringify({email:$('email').value,password:$('password').value})});$('loginPanel').classList.add('hidden');$('dashboard').classList.remove('hidden');await load();}catch(err){$('loginStatus').textContent=err.message;}};
$('logout').onclick=async()=>{await api('/api/admin/logout',{method:'POST'}).catch(()=>{});location.reload();};
$('inventory').onchange=async e=>{const el=e.target;if(!el.dataset.i)return;const p={...products[Number(el.dataset.i)]};p[el.dataset.k]=el.type==='checkbox'?el.checked:(el.dataset.k==='price'||el.dataset.k==='stock'?Number(el.value):el.value);try{await api('/api/admin/products',{method:'PUT',body:JSON.stringify(p)});$('dashStatus').textContent='Saved.';setTimeout(()=>$('dashStatus').textContent='',1200);}catch(err){$('dashStatus').textContent=err.message;}};
$('inventory').onclick=async e=>{const i=e.target.dataset.delete;if(i===undefined)return;if(!confirm(`Delete ${products[i].name}?`))return;await api('/api/admin/products',{method:'DELETE',body:JSON.stringify({id:products[i].id})});await load();};
$('addProduct').onclick=async()=>{const name=prompt('Product name');if(!name)return;const category=prompt('Category','Vegetables')||'Other';const price=Number(prompt('Price','5'));const stock=Number(prompt('Stock','10'));await api('/api/admin/products',{method:'POST',body:JSON.stringify({name,category,price,stock,active:true,emoji:'🌿',note:'Carefully sourced'})});await load();};
(async()=>{try{await api('/api/admin/products');$('loginPanel').classList.add('hidden');$('dashboard').classList.remove('hidden');await load();}catch{}})();
