const FALLBACK_PRODUCTS = [
  {id:'fruit-box',name:'Fruit & Veg Box',category:'Boxes',price:28,emoji:'🥕',note:'Seasonal selection',stock:20},
  {id:'salad',name:'Organic Salad',category:'Salads',price:4.5,emoji:'🥬',note:'Fresh & crisp',stock:30},
  {id:'juice',name:'Organic Juice',category:'Juices',price:4,emoji:'🧃',note:'Cold pressed',stock:24},
  {id:'honey',name:'Local Honey',category:'Honey',price:7.5,emoji:'🍯',note:'Trusted local producer',stock:18},
  {id:'eggs',name:'Organic Eggs',category:'Eggs',price:4.5,emoji:'🥚',note:'Free-range',stock:30},
  {id:'jam',name:'Organic Jam',category:'Preserves',price:5.5,emoji:'🍓',note:'Small-batch',stock:20},
  {id:'carrots',name:'Fresh Carrots',category:'Vegetables',price:2.5,emoji:'🥕',note:'Seasonal',stock:40},
  {id:'tomatoes',name:'Vine Tomatoes',category:'Vegetables',price:3.5,emoji:'🍅',note:'Ripe & juicy',stock:40}
];
const CART_KEY='meadow_cart_v2';let products=[];let cart=JSON.parse(localStorage.getItem(CART_KEY)||'[]');let active='All';
const money=n=>`£${Number(n).toFixed(2)}`;const saveCart=()=>localStorage.setItem(CART_KEY,JSON.stringify(cart));const escapeHtml=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
async function loadProducts(){try{const r=await fetch('/api/products');if(!r.ok)throw 0;products=await r.json()}catch{products=FALLBACK_PRODUCTS}products=products.filter(p=>p.active!==false&&Number(p.stock??0)>0);render();renderCart()}
function renderCats(){const cats=document.getElementById('categories');if(!cats)return;const list=['All',...new Set(products.map(p=>p.category))];cats.innerHTML=list.map(c=>`<button class="cat ${c===active?'active':''}" data-cat="${escapeHtml(c)}">${escapeHtml(c)}</button>`).join('');cats.querySelectorAll('button').forEach(b=>b.onclick=()=>{active=b.dataset.cat;render()})}
function render(){renderCats();const grid=document.getElementById('productGrid');if(!grid)return;const shown=active==='All'?products:products.filter(p=>p.category===active);grid.innerHTML=shown.map(p=>`<article class="product-card"><div class="product-art">${escapeHtml(p.emoji||'🌿')}</div><div class="product-body"><small>${escapeHtml(p.category).toUpperCase()}</small><h3>${escapeHtml(p.name)}</h3><span>${escapeHtml(p.note||'Carefully sourced')}</span><div class="price-row"><span class="price">${money(p.price)}</span><button class="add" data-id="${escapeHtml(p.id)}">Add to basket</button></div></div></article>`).join('');grid.querySelectorAll('.add').forEach(b=>b.onclick=()=>add(b.dataset.id))}
function add(id){const p=products.find(x=>x.id===id);if(!p)return;const line=cart.find(x=>x.id===id&&!x.customBox);if(line)line.qty=Math.min(line.qty+1,Number(p.stock));else cart.push({id,qty:1});saveCart();renderCart();if(drawer)openCart();else window.location.href='index.html#shop'}
function addCustomBox(boxSize,boxItems){const sizes={small:{label:'Small',count:8,price:19},medium:{label:'Medium',count:11,price:25},large:{label:'Large',count:14,price:31}};const s=sizes[boxSize];if(!s||!Array.isArray(boxItems))return;const clean=boxItems.filter(x=>Number(x.qty)>0).map(x=>({id:String(x.id),qty:Math.floor(Number(x.qty))}));if(clean.reduce((n,x)=>n+x.qty,0)!==s.count)return alert(`Please choose exactly ${s.count} items for the ${s.label} box.`);cart.push({id:`custom-box-${boxSize}`,qty:1,customBox:true,boxSize:s.label,itemCount:s.count,price:s.price,selections:clean});saveCart();renderCart();window.location.href='index.html#shop'}
window.addCustomBox=addCustomBox;window.getBoxProducts=()=>products.filter(p=>p.category!=='Boxes');
function change(id,d){const l=cart.find(x=>x.id===id),p=products.find(x=>x.id===id);if(!l)return;if(l.customBox){if(d<0)cart=cart.filter(x=>x!==l);saveCart();renderCart();return}if(!p)return;l.qty+=d;if(l.qty>Number(p.stock))l.qty=Number(p.stock);if(l.qty<1)cart=cart.filter(x=>x.id!==id);saveCart();renderCart()}
function cartTotal(){return cart.reduce((s,l)=>{if(l.customBox)return s+Number(l.price)*Number(l.qty);const p=products.find(x=>x.id===l.id);return s+(p?Number(p.price)*l.qty:0)},0)}
function renderCart(){const box=document.getElementById('cartItems');if(!box)return;cart=cart.filter(l=>l.customBox||products.some(p=>p.id===l.id));let count=0;box.innerHTML=cart.length?cart.map(l=>{count+=Number(l.qty)||0;if(l.customBox){const names=(l.selections||[]).map(s=>{const p=products.find(x=>x.id===s.id);return p?`${escapeHtml(p.name)} × ${s.qty}`:escapeHtml(s.id)}).join(', ');return `<div class="cart-line"><div class="cart-thumb">🌿</div><div><b>${escapeHtml(l.boxSize)} organic box</b><div class="qty"><span>${l.itemCount} items</span><button data-id="${escapeHtml(l.id)}" data-d="-1">Remove</button></div><small>${names}</small></div><strong>${money(Number(l.price)*Number(l.qty))}</strong></div>`}const p=products.find(x=>x.id===l.id);return `<div class="cart-line"><div class="cart-thumb">${escapeHtml(p.emoji||'🌿')}</div><div><b>${escapeHtml(p.name)}</b><div class="qty"><button data-id="${p.id}" data-d="-1">−</button><span>${l.qty}</span><button data-id="${p.id}" data-d="1">+</button></div></div><strong>${money(Number(p.price)*l.qty)}</strong></div>`}).join(''):'<p>Your basket is waiting for something wholesome.</p>';box.querySelectorAll('button').forEach(b=>b.onclick=()=>change(b.dataset.id,Number(b.dataset.d)));document.getElementById('cartTotal').textContent=money(cartTotal());document.getElementById('cartCount').textContent=count}
const drawer=document.getElementById('cartDrawer'),backdrop=document.getElementById('backdrop'),checkoutModal=document.getElementById('checkoutModal');
function openCart(){drawer?.classList.add('open');backdrop?.classList.add('show');drawer?.setAttribute('aria-hidden','false')}
function closeCart(){drawer?.classList.remove('open');backdrop?.classList.remove('show');drawer?.setAttribute('aria-hidden','true')}
function ensurePaymentOptions(){const form=document.getElementById('checkoutForm');if(!form||document.getElementById('paymentMethod'))return;const wrap=document.createElement('div');wrap.className='checkout-field full';wrap.innerHTML='<label>PAYMENT METHOD</label><div class="payment-options"><label class="payment-option"><input id="payOnline" type="radio" name="paymentMethod" value="online" checked><span><strong>Pay online</strong><small>Secure payment by Dojo</small></span></label><label class="payment-option"><input id="payCash" type="radio" name="paymentMethod" value="cash"><span><strong>Cash on delivery</strong><small>Pay when your order arrives</small></span></label></div>';const summary=form.querySelector('.checkout-summary');form.insertBefore(wrap,summary);}
function openCheckout(){if(!cart.length)return alert('Your basket is empty.');ensurePaymentOptions();document.getElementById('checkoutTotal').textContent=money(cartTotal());const d=new Date();d.setDate(d.getDate()+1);document.getElementById('deliveryDate').min=d.toISOString().slice(0,10);checkoutModal.classList.add('show');checkoutModal.setAttribute('aria-hidden','false');closeCart()}
function closeCheckout(){checkoutModal.classList.remove('show');checkoutModal.setAttribute('aria-hidden','true')}
document.getElementById('openCart')?.addEventListener('click',openCart);document.getElementById('closeCart')?.addEventListener('click',closeCart);backdrop?.addEventListener('click',closeCart);document.getElementById('checkoutButton')?.addEventListener('click',openCheckout);document.getElementById('checkoutClose')?.addEventListener('click',closeCheckout);checkoutModal?.addEventListener('click',e=>{if(e.target===checkoutModal)closeCheckout()});
document.querySelector('.mobile-toggle')?.addEventListener('click',()=>{const n=document.getElementById('nav');n.classList.toggle('show');document.querySelector('.mobile-toggle').setAttribute('aria-expanded',n.classList.contains('show'))});
document.getElementById('checkoutForm')?.addEventListener('submit',async e=>{e.preventDefault();const error=document.getElementById('checkoutError'),pay=document.getElementById('payButton');error.textContent='';pay.disabled=true;const paymentMethod=document.querySelector('input[name="paymentMethod"]:checked')?.value||'online';pay.textContent=paymentMethod==='cash'?'Placing cash-on-delivery order…':'Opening secure Dojo payment…';try{const body={name:document.getElementById('customerName').value.trim(),email:document.getElementById('customerEmail').value.trim(),phone:document.getElementById('customerPhone').value.trim(),deliveryDate:document.getElementById('deliveryDate').value,paymentMethod,items:cart};const r=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Checkout could not be started');window.location.href=data.url}catch(err){error.textContent=err.message;pay.disabled=false;pay.textContent=paymentMethod==='cash'?'Place cash-on-delivery order':'Continue to secure payment'}});
loadProducts();